### ISSUE TITLE
problem of downloading earthquake data

### ISSUE THREAD

**Issue by EDAPINENUT** [facebookresearch/neural_stpp#9]
The earthquake file downloaded by ./data/download_and_preprocess_earthquakes.py :  download_data can not be obtained.

'''
Traceback (most recent call last):
  File "download_and_preprocess_earthquakes.py", line 65, in <module>
    filenames.append(download_data(1990, 1999))
  File "download_and_preprocess_earthquakes.py", line 17, in download_data
    urllib.request.urlretrieve(url, filename)
  File "/opt/anaconda3/envs/STNN/lib/python3.7/urllib/request.py", line 257, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'earthquakes/1990_1999.csv'
'''

**Comment by rtqichen** [comment]
Thanks for the report. Should be fixed by fab3c26272faf4fe4fbb0014553a625cbef533b1.
